### ISSUE TITLE
VSPAERO crash with fuselage geometry

### ISSUE THREAD

**Issue by aecaen** [OpenVSP/OpenVSP#129]
I have had issues with VSPAERO crashing when the fuselage is built from rounded rectangles.  This occurred in both 3.17 and 3.18 versions.  Thanks.

**Comment by ramcdona** [comment]
This is an unfortunate known problem with VLM and Rounded rectangles.  OpenVSP's DegenGeom smashes the sides down -- since they are parallel, they form degenerate panels which cause the VLM to crash.

The workaround is to create a duplicate fuselage with ellipse cross sections for VLM analysis.  You can use Sets to keep both the ellipse and 'normal' XSec in the model.
