### ISSUE TITLE
VSP3.19.1 tiny bug VSPAERO mom ref position

### ISSUE THREAD

**Issue by marcovanderbijl** [OpenVSP/OpenVSP#139]
in OpenVSP 3.19.1
VSPAERO
moment reference position Mass set pull down selection menu correctly displays up to set 19. however it only wants to calculate the mass upto set 9

**Comment by ramcdona** [comment]
Thanks for pointing this out.  

It is caused because the maximum value of the m_CGGeomSet (here https://github.com/OpenVSP/OpenVSP/blob/master/src/geom_core/VSPAEROMgr.cpp#L59) was not increased when we increase the maximum number of Sets to 20 in d05757b849560.

@justingravett -- this is likely a bug that shows up in a number of places.  I don't know an easy way to search for these beyond a manual audit.  We should come up with a #define or something such that this bug can't reoccur.
