### ISSUE TITLE
Prop surface ripples when using blade t/c and closure.

### ISSUE THREAD

**Issue by litherlandbrandon** [OpenVSP/OpenVSP#146]
There seems to be an interaction with t/c scaling and the added thickness from adjusting a trailing edge closure that causes the Prop surface to ripple between control points in the model.  This presented itself with the new Blade t/c control (3.18.0?) and persists as of 3.20.1.

This problem can occur with multiple cross-section types.  Create a default prop > adjust XSec 0 and 1 to have TE Closure of 0.1 > notice the dip between sections.

**Comment by ramcdona** [comment]
The problem is an interaction between the t/c scaling that props now do (so you can have a thickness distribution) and the added thickness by thickening the trailing edge.  The problem is with the order -- the 'hard' file airfoils are scaled to the target t/c then thickened for the blunt TE (they now have greater than the target t/c).  Those 'complete' airfoils are then interpolated for intermediate points and then scaled to match the target t/c -- so they are thinner than the 'hard' airfoils.

The problem will show when the propeller foil interpolation ends up going through the [generic code here](https://github.com/OpenVSP/OpenVSP/blob/master/src/geom_core/PropGeom.cpp#L666).

Solutions include calculating a t/c correction -- difficult because the point of max thickness is not fixed.  Or interpolate the airfoils before the TE modifications are applied (major surgery, likely to have complications, etc).  Or turn off t/c scaling with certain airfoil types (bad because it is a good feature).  Or something else...
