### ISSUE TITLE
Hinge does not respect absolute positioning of child components

### ISSUE THREAD

**Issue by HaddocktheHorrible** [OpenVSP/OpenVSP#159]
Child elements of Hinge will move as the hinge is translated/rotated through XForm even if child elements are defined using the "Abs" coordinate system. I suppose this is an artifact of how the absolute position is updated when the hinge rotation is changed? Absolute position update with hinge motion makes sense, but updates with hinge XForm translations seems like a bug.

I am using OpenVSP 3.21.2 x64 (windows)

Cheers,
-Edward

**Comment by ramcdona** [comment]
This is actually true for all components that are attached to their parents, not just hinges.  You may have noticed it because hinges are forced to be attached.

Absolute XForm isn't as absolute as the name makes it seem....

When something is attached, it needs to move when the parent moves.  Otherwise, attachment wouldn't make sense.  We could either disable absolute positioning when attached (or disable attachment when abs is used).  Either of those would really hamstring attachment as a useful feature.

Instead, we trick our way around the problem.  When position is updated (hinge or not), all components are switched to relative, position is updated, and then they are switched back to absolute if that is the mode they were in.

So, absolute does not lock in the position of a component -- it is the position of the component in an absolute coordinate system.

Usually these kinds of questions are handled on the Google Group.
