### ISSUE TITLE
Trimmed Surfaces - Export Bug

### ISSUE THREAD

**Issue by sercanertem** [OpenVSP/OpenVSP#195]
Hi everyone,

I am having trouble when using "Trimmed Surfaces" interface and I wanted to share, since I think it is some kind of a bug. 
The problem I encounter happens when I export trimmed IGES from the the attached VSP project. The name tags of surfaces become all mixed up. Somehow trimmed export loses its ties to the component names in VSP project. This does not happen during untrimmed IGES export. For this specific VSP project, I have notified that when I remove the sub-components of FuselageGeom (Canopy,Pod,Engine), the exported trimmed surfaces have the correct name tags. So the problem is somehow related to the fuselage for this case.  I have generated this file in VSP 3.21.2 but also tested in 3.25.0. 

Attached zip file contains following files:
- the VSP project
- trimmed IGES file with erroneous surface namings

[TestAircraft.zip](https://github.com/OpenVSP/OpenVSP/files/7016480/TestAircraft.zip)

**Comment by justingravett** [comment]
It looks like there was a mismatch in the Surf ID vs index in the Surf vector. This is because some surfaces are dropped during the trimmed export process, such as those on a sharp trailing or leading edge. I've attached the correct labeling for your example file, so please let me know how it looks. Had to put it in a Zip file since IGS extensions are not accepted
[TestAircraft.zip](https://github.com/OpenVSP/OpenVSP/files/7041534/TestAircraft.zip)
