### ISSUE TITLE
Bug report: axes with propellers

### ISSUE THREAD

**Issue by John-Bucknell** [OpenVSP/OpenVSP#21]
If a propeller is inserted and rotated such that the axis of rotation is close to the Z-axis (as in a lifting rotor), no rotation about the actual Z is possible (ie to index the blades).  Moving the Z and X slider both produce the same rotation.

**Comment by ramcdona** [comment]
In v3, you can create a propeller by using a wing component with radial symmetry.

In v2 or v3, you should create the prop as a child of a 'Blank' component.  Then, attach the prop to the blank.  The blank component acts as a coordinate system, enabling all the rotations you can't achieve otherwise.

You'll find that using component attachment can enable sophisticated articulation of models.

**Comment by John-Bucknell** [comment]
Hi Rob,
I think OpenVSP has been down all morning.  Getting a Wordpress error as of now "Your PHP installation appears to be missing the MySQL extension which is required by WordPress.".
John
