### ISSUE TITLE
incoherent results with OpenVSP

### ISSUE THREAD

**Issue by RaphP31** [OpenVSP/OpenVSP#227]
A vertical tail wing (of an aircraft, NACA 0012) is simulated in OpenVSP, 3.27.1-win64.
The angle in z (deflection) is changed from -10° to +10°
One would expect the results to be symmetric, however this is not the case.

![image](https://user-images.githubusercontent.com/104492367/165479277-26854f47-58af-4287-93be-94e3e2dbc83e.png)

For a deflection (Xrot)= -10°, I found : 

![image](https://user-images.githubusercontent.com/104492367/165479890-5621c825-8bc6-45e8-ad06-fa5934f390ef.png)

And for Xrot = 10°

![image](https://user-images.githubusercontent.com/104492367/165481037-508dc104-ee73-486e-b072-2684a9be414e.png)

As punctual calculation for each value of alpha, I didn't find exactly the same results as previously but the gap is negligible (10E-6)

Do I missed something?

I included .vsp3 file as .txt for enable upload :
[Y Vertical Tail.txt](https://github.com/OpenVSP/OpenVSP/files/8570653/Y.Vertical.Tail.txt)

**Comment by ramcdona** [comment]
This kind of question is better handled on the Google Group.  More people check that more frequently.

We mainly use GitHub issues to track known bugs.

You've rotated the tail to be vertical by using dihedral 90 degrees -- without rotating the foils to match dihedral.  This results in a thin wing instead of something with actual thickness.

Instead, the best practice is to achieve a vertical tail by rotating the tail 90 degrees about the X axis.

You have also rotated the wing about Z by 15 degrees, this is similar to a wing in sideslip -- you then do an alpha sweep.  I would expect a side-force in this case -- and it would likely change with alpha.

Your model uses numbers of very high magnitude -- perhaps you are modeling your aircraft in mm.  While it should theoretically work, some of the algorithms in OpenVSP are not well tested for very large or very small magnitude numbers.  I recommend you model your aircraft in feet or meters to get the best results.
