### ISSUE TITLE
Secondary Sweep Error

### ISSUE THREAD

**Issue by SteveDoyle2** [OpenVSP/OpenVSP#76]
I'm using OpenVSP 3.11.0 and I ran into an error when creating a **Wing** using the **Span**, **Root Chord**, and **Tip Chord** options.  I tried to set the **Sweep Location** to 1 (the same as the **Secondary Sweep Location**), which raised an error.

    Error: Attempt to set Sweep_Location equal to Sec_Sweep_Location.

As I wasn't using **Secondary Sweep Location**, I expected:
  1) the **Secondary SW Loc** field to be greyed out
  2) no error message

Changing the unused **Secondary SW Loc** field to another value fixed the error.

Thanks again for the hard work!

Steve

**Comment by ramcdona** [comment]
While admittedly confusing, this one is a 'feature'.

In order to define a wing with both a primary and secondary sweep angle, those two angles have to be defined about different locations.  Consequently, their locations can not be equal.  OpenVSP pops up an error message when the user tries to set them equal from the GUI or from scripting.

The logical default for secondary sweep location is 1.0 -- but this is also a highly likely setting for the primary sweep location.  Consequently, people run into this fairly regularly.

Your solution is what I expect users to do.  Change secondary sweep location to some other value, then change primary sweep location to 1.0.
