### ISSUE TITLE
Feature Request: Scripting Macro

### ISSUE THREAD

**Issue by benjamincorr** [OpenVSP/OpenVSP#91]
Most script-based-users (which should be everyone) make their "X0" initial design in the GUI, and then go through the painstaking process of building a script which builds that same design, and then they template the script so it can be run though an optimizer or other design iteration tool.

Every component has default values (example: trap wing defaults to a default airfoil, span, dihedral, ...) and the user "tweaks" these values via the GUI. It should be easy enough to generate a diff of the defaults and the current values, and then create an AngleScript that declares each component and then sets non-default attributes. This would make for a very clean workflow of building the initial design in the GUI and "exporting" it to a script.

*Follow-On Feature Request: When exporting to a script, the export dialog includes a table with each non-default value as a column and the values in the GUI as the first row. The user can then fill in more rows of the table. For each row of the table a script is exported. For example, the GUI, and thus first row, would have the initial design and the following rows would have the "corner-case" or design-of-experiments configurations which could be used to make a regression model of the design space.

**Comment by ramcdona** [comment]
I agree that some users work this way -- but I really don't understand why so many insist on re-building a model from scratch rather than simply modifying parameters on an already existing model.

Simply loading a model, tweaking a handful of parameters, Update() and then export the desired format is a lot easier than building a model from scratch every time.
